### ISSUE TITLE
Implement a PLL in the phase domain

### ISSUE THREAD

**Issue by zzaahhrraa1994** [mhostetter/sdr#191]
Hello, thank you for the new changes you made, but when I run the examples
phase-locked-loop.ipynb I have a problem with Implement a PLL in the phase domain. My output when running the program is the form I have sent in the attachment. Please solve my problem. Thank you very much.
![c 2 5](https://github.com/mhostetter/sdr/assets/108925761/3775788f-0c69-47af-9d0d-7e1b8847c111)
![c 2 5](https://github.com/mhostetter/sdr/assets/108925761/e639f7fd-503b-43a9-81b0-9674d24e4e1b)

**Comment by mhostetter** [comment]
Did you install the code from the `release/0.0.x` branch? It seems you're running v0.0.10.

**Comment by zzaahhrraa1994** [comment]
I have installed release/0.0.x.

**Comment by zzaahhrraa1994** [comment]
I am sure that I have installed the release/0.0.x version, because if I had installed it wrongly, I would have had problems with the Implement a PLL in the time domain section, but it runs correctly, but the results in the Implement a PLL in the phase domain section are not correct.

**Comment by mhostetter** [comment]
Do you have this line in the cell above the plot? You should. This was added in my latest PR.

```python
    # Process the variable phase increment through the NCO
    y[i + 1] = nco(freq_estimate[i], output="phase")
```

If it is ` y[i + 1] = nco(freq_estimate[i])` that will explain the output you are seeing, which is incorrect.

**Comment by zzaahhrraa1994** [comment]
y[i + 1] = nco(freq_estimate[i], output="phase" When I run this line, I get the error nco has no output argument)

**Comment by mhostetter** [comment]
That is because you don't have the latest `release/0.0.x` installed, as I previously suspected. Reference this document https://mhostetter.github.io/sdr/latest/development/installation/.

You'll want to: clone the repo, fetch, checkout `release/0.0.x`, and run `python -m pip install -e .`.

**Comment by zzaahhrraa1994** [comment]
Thank you very much for your guidance. The problem is solved. Thank you

**Comment by mhostetter** [comment]
The example was just added in `release/0.0.x`.
