### ISSUE TITLE
psk

### ISSUE THREAD

**Issue by zzaahhrraa1994** [mhostetter/sdr#192]
My purpose of reading the document of your project is to perform demodulation of digital signals including psk and qam. Can you help me in this field and give me an example of demodulation of these signals? Thank you.

**Comment by mhostetter** [comment]
I have worked hard to make the documentation thorough and robust. It can be improved, however I don't have the time to make custom tutorials and examples.

See these links for my current documentation on PSK. Continue to monitor the project. More examples and functionality will come with time.
- https://mhostetter.github.io/sdr/latest/examples/psk/
- https://mhostetter.github.io/sdr/latest/api/sdr.PSK/
- https://mhostetter.github.io/sdr/latest/api/sdr.PSK/#methods.
